"""empty message

Revision ID: 891be97a23ef
Revises: 
Create Date: 2019-11-23 15:15:06.377915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891be97a23ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('totp_secret', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('balance',
    sa.Column('seller', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['user_login.uid'], ),
    sa.ForeignKeyConstraint(['seller'], ['user_login.uid'], ),
    sa.PrimaryKeyConstraint('seller', 'buyer')
    )
    op.create_table('invoice',
    sa.Column('iid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('items', sa.String(length=2137), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payable', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer'], ['user_login.uid'], ),
    sa.ForeignKeyConstraint(['seller'], ['user_login.uid'], ),
    sa.PrimaryKeyConstraint('iid')
    )
    op.create_table('user_config',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('default_currency', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user_login.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_invoice',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('tin', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user_login.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('tin')
    )
    op.create_table('transaction',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('invoice', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer'], ['user_login.uid'], ),
    sa.ForeignKeyConstraint(['invoice'], ['invoice.iid'], ),
    sa.ForeignKeyConstraint(['seller'], ['user_login.uid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user_invoice')
    op.drop_table('user_config')
    op.drop_table('invoice')
    op.drop_table('balance')
    op.drop_table('user_login')
    # ### end Alembic commands ###
